### ISSUE TITLE
some questions about the released model

### ISSUE THREAD

**Issue by tyistyler** [SVAIGBA/WMSeg#5]
您好，我在使用您提供的已训练好的模型进行测试时，发现有两个模型的结果与论文结果不符，其余六个模型的结果都与符合论文，测试结果如下图所示，其中加粗部分为出错的两个模型。
我使用的环境为python3.7+torch1.4，请问是跟您环境（python3.6+torch1.1）不符导致的么？

![捕获](https://user-images.githubusercontent.com/49506255/91259718-9c860080-e7a1-11ea-97b0-edcfea93c14d.PNG)

_Originally posted by @tyistyler in https://github.com/SVAIGBA/WMSeg/issues/3#issuecomment-680668402_

**Comment by yuanheTian** [comment]
> 您好，我在使用您提供的已训练好的模型进行测试时，发现有两个模型的结果与论文结果不符，其余六个模型的结果都与符合论文，测试结果如下图所示，其中加粗部分为出错的两个模型。
> 我使用的环境为python3.7+torch1.4，请问是跟您环境（python3.6+torch1.1）不符导致的么？
> 
> ![捕获](https://user-images.githubusercontent.com/49506255/91259718-9c860080-e7a1-11ea-97b0-edcfea93c14d.PNG)
> 
> _Originally posted by @tyistyler in [#3 (comment)](https://github.com/SVAIGBA/WMSeg/issues/3#issuecomment-680668402)_

感谢您指出这两个模型的问题。

我们可能错误地上传了在别的数据集上训练的模型（不然 Recall OOV 不会这么高）。我们已经更新了您提到的两个模型。新模型 F 值与文章中汇报的一致，Recall OOV 会略高于文中的值。
