### ISSUE TITLE
The results of CTB6 cannot be reproduced on the trained model

### ISSUE THREAD

**Issue by LzhinFdu** [SVAIGBA/WMSeg#6]
On the given trained model, we reproduced the results of CityU and other data sets very well, but when we used the given trained model to test the performance of CTB6, we found that the f1 value was only 92.6(ZEN) and 92.2(BERT). Can you help me point out the causes of this problem?

**Comment by yuanheTian** [comment]
Thank you for pointing out.

It seems that we upload a model trained on other datasets for some reason.

We re-uploaded the correct models. You can check them out now.

For reference, the MD5 code for the two model files are:
WMSeg.BERT.CTB6: 3655aad4078db9e0f2a8d37b3b5eae4e
WMSeg.ZEN.CTB6: 96435c5d2c4e99f569a5c9945723f844

**Comment by Ac-Zyx** [comment]
I use the new model, but the effect on CTB is not as good as in the paper

**Comment by yuanheTian** [comment]
> I use the new model, but the effect on CTB is not as good as in the paper

Did you use the official CTB6 dataset (https://catalog.ldc.upenn.edu/LDC2007T36) and obtain the splits by our code?

I know there is another dataset named CTB which is different from the CTB6 used in our study.
